[package]
name = "profile"
version = "0.1.0"
authors = ["beem"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.10", features = ["serde"] }
diesel = { version = "1.4.3", features = ["postgres", "chrono"] }
dotenv = "0.15.0"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
serde_derive = "1.0"
lazy_static = "1.4.0"
r2d2 = "0.8.8"
r2d2-diesel = "1.0.0"
rocket = "0.4.2"
rocket_contrib = { version = "0.4.2", features = ["json"] }
rocket_codegen = "0.4.2"
bcrypt = "0.6"
validator = "0.10"
validator_derive = "0.10"
jsonwebtoken = "5"
time = "0.1"
rocket_cors = "0.5.1"
oauth2 = "2.0.0"
base64 = "0.12.0"
url = "1.7.2"
rand = "0.7.3"
